docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Introduction: intro.md
    - Usage: usage.md
    - Reference:
        - 'Barcode Objects': objects.md
        - 'Renderers': renderers.md
site_name: laminas-barcode
site_description: Laminas\Barcode
repo_url: 'https://github.com/laminas/laminas-barcode'
